// <auto-generated />
using System;
using AmiyaBotPlayerRatingServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmiyaBotPlayerRatingServer.Migrations
{
    [DbContext(typeof(PlayerRatingDatabaseContext))]
    [Migration("20230827095107_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmiyaBotPlayerRatingServer.Model.CharacterStatistics", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AverageExptLevel")
                        .HasColumnType("integer");

                    b.Property<int>("AverageLevel")
                        .HasColumnType("integer");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VersionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VersionStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CharacterStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
