# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
          cd AmiyaBotPlayerRatingServer
          dotnet publish -c Release -o ../publish
          ls -ltr ../
    - name: Login to Private Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.hsyhhssyy.net
        username: hsyhhssyy@example.com
        password: ${{ secrets.HARBOR_PUSH_KEY }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: harbor.hsyhhssyy.net/home-esxi/amiya-bot-player-rating-server:latest
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      id: install
    - name: Write Context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.HOMECLOUD_KUBECONFIG }}
      id: setcontext
    - name: Push to k8s
      uses: Azure/k8s-deploy@v4
      with:
        namespace: 'amiya-bot'
        manifests: pod.yaml
        images: 'harbor.hsyhhssyy.net/home-esxi/amiya-bot-player-rating-server:latest'